modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "custom_mobs"
version = "${version}"
displayName = "Custom Mobs Framework"
authors = "Azureddraig"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.custom_mobs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custom_mobs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custom_mobs]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
